# Generated by Django 4.0.2 on 2022-02-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Insurance',
            new_name='insurance',
        ),
    ]
