# Generated by Django 4.0.2 on 2022-04-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit_operation',
            name='operationID',
        ),
        migrations.RemoveField(
            model_name='visit_operation',
            name='visitID',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='Visit_Operation',
        ),
    ]
