# Generated by Django 4.0.2 on 2022-04-17 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_user_accountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accountID',
            field=models.OneToOneField(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='user',
            name='roleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
    ]
