# Generated by Django 4.0.4 on 2022-04-23 09:45

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appointment_date_alter_appointment_doctorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ClinicID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.clinic', verbose_name='Clinic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=12, verbose_name='Default Price'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mail',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email address'),
        ),
    ]
