# Generated by Django 4.0.2 on 2022-04-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_accountid_alter_user_roleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accountID',
        ),
    ]
