# Generated by Django 4.0.2 on 2022-02-28 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clinic_journalentrytype_operation_paymentjournal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='appointmemt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 12, 50, 27, 376265)),
        ),
    ]
