# Generated by Django 4.0.2 on 2022-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_accountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
