# Generated by Django 4.0.4 on 2022-04-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_visit_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit_operation',
            old_name='visitoperation',
            new_name='visit',
        ),
    ]
