# Generated by Django 4.0.2 on 2022-03-10 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appointment_rename_clinic_operation_clinicid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 16, 41, 14, 977483)),
        ),
    ]
