# Generated by Django 4.0.4 on 2022-04-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_visitoperation_visit_operation_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit_operation',
            old_name='visit',
            new_name='visitID',
        ),
    ]
