# Generated by Django 4.0.4 on 2022-04-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_visit_visit_operation_visitid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit_operation',
            name='operation',
        ),
        migrations.AddField(
            model_name='visit_operation',
            name='operation',
            field=models.ManyToManyField(to='api.operation'),
        ),
    ]
