# Generated by Django 3.2.13 on 2022-04-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_visit_operation_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ClinicID',
        ),
    ]
