# Generated by Django 3.2.13 on 2022-04-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_patient_clinicid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='comments',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
